<a href="https://colab.research.google.com/github/luismenco2315-cpu/Prog_Civil_2026_1/blob/main/2_3_4_Actividad_Pluma_de_Agua_Algoritmo_GitHub.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NOMBRES COMPLETOS: Luis Mario Menco Gaviria
# Código: 1102581531

# Actividad de Programación con Python  
## **Historia, ciencia y programación: la “pluma de agua”**

> **Relato de partida**  
> **¿Por qué los costeños le decimos “pluma” a la llave del agua?**  
>  
> En el Caribe colombiano, abrir la “pluma” no es solo una acción cotidiana: es una expresión cargada de historia, técnica y cultura. Aunque algunos se sorprendan o incluso se burlen del término, lo cierto es que decir “pluma” en vez de “llave” no es un error, sino una herencia viva que conecta nuestro lenguaje con siglos de evolución hidráulica.  
>  
> Mucho antes de que existieran los grifos modernos, el agua se distribuía mediante sistemas regulados con precisión. En España, por ejemplo, se usaba la **“pluma de agua”** como unidad de medida para calcular el caudal que se entregaba a cada hogar. Aproximadamente, una pluma equivalía a **0.025 litros por segundo**. En algunos lugares, ese flujo se regulaba mediante orificios calibrados y dispositivos llamados **plumeros**, que permitían controlar la salida del agua.  
>  
> Durante la época colonial, muchas de estas prácticas técnicas cruzaron el Atlántico y llegaron a ciudades como Cartagena, Barranquilla y Santa Marta. Con el tiempo, el término “pluma” dejó de ser solamente técnico y pasó al habla cotidiana como sinónimo de la llave del agua.  
>  
> Así, una palabra del uso diario conserva una memoria histórica, tecnológica y cultural.  
>  
> ---
>  
> **Idea central para esta actividad:**  
> A partir de este relato, construiremos un problema de programación donde una magnitud histórica y física, el **caudal de una pluma de agua**, se represente mediante variables, operaciones y estructuras básicas de Python.

## 1. Propósito de la actividad

Al finalizar esta actividad, el estudiante debe ser capaz de:

- interpretar un contexto histórico y científico como un problema computacional;
- identificar entradas, procesos y salidas;
- diseñar un algoritmo antes de programar;
- implementar el programa en Python;
- publicar el trabajo en GitHub;
- ampliar la documentación del código;
- clonar el repositorio al disco local usando Git.

> **Importante:**  
> En este notebook **no se entrega la solución completa**.  
> Aquí se presenta el **planteamiento**, la **estructura del problema** y el **algoritmo guía** para que cada estudiante construya el código.

## 2. Situación problema

Un hogar recibe una cierta cantidad de **plumas de agua**.  
Se sabe que:

- **1 pluma = 0.025 litros por segundo**

Con esta información, el estudiante debe construir un programa que permita calcular:

1. el caudal total en litros por segundo;
2. el consumo diario en litros;
3. el consumo mensual en litros (suponiendo 30 días);
4. una clasificación del consumo:
   - **Bajo**: menos de 1000 litros por día
   - **Medio**: entre 1000 y 3000 litros por día
   - **Alto**: más de 3000 litros por día

---

## 3. Análisis del problema

### 3.1 Entrada del sistema
El programa debe recibir:

- número de plumas asignadas al hogar.

### 3.2 Proceso
El programa debe:

- convertir el número de plumas en caudal total;
- transformar el caudal a consumo diario;
- transformar el consumo diario a consumo mensual;
- clasificar el nivel de consumo.

### 3.3 Salida
El programa debe mostrar:

- caudal total;
- consumo diario;
- consumo mensual;
- clasificación del consumo.

## 4. Variables y constantes sugeridas

El estudiante puede trabajar con variables como las siguientes:

- `plumas`
- `caudal_pluma`
- `caudal_total`
- `segundos_dia`
- `consumo_diario`
- `consumo_mensual`
- `nivel_consumo`

> Puede cambiar los nombres, pero deben ser claros y significativos.

## 5. Algoritmo propuesto

Antes de programar, escriba el algoritmo en lenguaje natural o seudocódigo.

### Algoritmo en lenguaje natural

1. Solicitar al usuario el número de plumas de agua.
2. Definir el valor de una pluma en litros por segundo.
3. Definir la cantidad de segundos que tiene un día.
4. Calcular el caudal total.
5. Calcular el consumo diario.
6. Calcular el consumo mensual.
7. Determinar si el consumo es bajo, medio o alto.
8. Mostrar los resultados de manera clara.

### Seudocódigo guía

```text
Inicio
    Leer número de plumas
    Definir caudal de una pluma
    Definir segundos por día

    Calcular caudal total
    Calcular consumo diario
    Calcular consumo mensual

    Si consumo diario es menor que 1000
        nivel = "Bajo"
    Si no, si consumo diario está entre 1000 y 3000
        nivel = "Medio"
    En otro caso
        nivel = "Alto"

    Mostrar caudal total
    Mostrar consumo diario
    Mostrar consumo mensual
    Mostrar nivel
Fin
```

## 6. Espacio para que el estudiante construya la solución

### Instrucciones
Complete el siguiente bloque de código a partir del algoritmo anterior.

- No copie una solución terminada sin comprenderla.
- Escriba comentarios propios.
- Use nombres de variables comprensibles.
- Verifique que los resultados tengan sentido físico.

In [ ]:
# ACTIVIDAD: MODELAR LA "PLUMA DE AGUA" CON PYTHON
# ==========================================================

# 1. Solicitar al usuario el número de plumas
plumas = float(input("Ingrese el número de plumas: "))

# 2. Definir constantes del problema
# Caudal de una pluma en litros por segundo
CAUDAL_PLUMA = 0.025 # litros/segundo
# Segundos en un día
SEGUNDOS_DIA = 24 * 60 * 60 # segundos
# Días en un mes para el cálculo (asumiendo 30 días)
DIAS_MES = 30

# 3. Calcular el caudal total (litros por segundo)
caudal_total = plumas * CAUDAL_PLUMA

# 4. Calcular el consumo diario (litros)
consumo_diario = caudal_total * SEGUNDOS_DIA

# 5. Calcular el consumo mensual (litros)
consumo_mensual = consumo_diario * DIAS_MES

# 6. Clasificar el consumo
nivel_consumo = ""
if consumo_diario < 1000:
    nivel_consumo = "Bajo"
elif 1000 <= consumo_diario <= 3000:
    nivel_consumo = "Medio"
else:
    nivel_consumo = "Alto"

# 7. Mostrar resultados
print(f"\n--- Resultados del Consumo de Agua ---")
print(f"Número de plumas: {plumas}")
print(f"Caudal total: {caudal_total:.3f} litros por segundo")
print(f"Consumo diario estimado: {consumo_diario:.2f} litros")
print(f"Consumo mensual estimado (30 días): {consumo_mensual:.2f} litros")
print(f"Clasificación del consumo: {nivel_consumo}")

Ingrese el número de plumas: 3

--- Resultados del Consumo de Agua ---
Número de plumas: 3.0
Caudal total: 0.075 litros por segundo
Consumo diario estimado: 6480.00 litros
Consumo mensual estimado (30 días): 194400.00 litros
Clasificación del consumo: Alto

## 7. Verificación conceptual

Antes de dar por terminado el programa, responda en comentarios o en una celda Markdown:

1. ¿Qué representa físicamente la variable principal del problema?
2. ¿Por qué este ejercicio conecta historia, cultura e ingeniería?
3. ¿Qué operaciones aritméticas fueron necesarias?
4. ¿Qué estructura condicional utilizó y por qué?
5. ¿Cómo interpretaría el resultado en un contexto real?

## Respuestas a las preguntas de verificación conceptual

1.  **¿Qué representa físicamente la variable principal del problema?**
    La variable principal `plumas` representa el número de unidades de "pluma de agua" asignadas a un hogar. Físicamente, esto se traduce en el caudal de agua que el hogar recibe por segundo, siendo `1 pluma = 0.025 litros/segundo`.

2.  **¿Por qué este ejercicio conecta historia, cultura e ingeniería?**
    Este ejercicio conecta:
    *   **Historia y cultura:** A través del término "pluma de agua", que es una herencia histórica y cultural del Caribe colombiano para referirse a la llave del agua, basada en antiguas unidades de medida de caudal.
    *   **Ingeniería:** Al aplicar cálculos y modelado de sistemas hidráulicos (caudal, consumo diario y mensual) y la clasificación del uso del agua, que son conceptos fundamentales en la ingeniería y gestión de recursos hídricos.

3.  **¿Qué operaciones aritméticas fueron necesarias?**
    Las operaciones aritméticas necesarias fueron principalmente la **multiplicación** para calcular:
    *   El caudal total (`plumas * CAUDAL_PLUMA`).
    *   El consumo diario (`caudal_total * SEGUNDOS_DIA`).
    *   El consumo mensual (`consumo_diario * DIAS_MES`).

4.  **¿Qué estructura condicional utilizó y por qué?**
    Se utilizó una estructura condicional `if-elif-else`. Esta estructura es ideal porque permite evaluar múltiples condiciones excluyentes para clasificar el consumo de agua (`Bajo`, `Medio`, `Alto`) basándose en el valor del `consumo_diario`.

5.  **¿Cómo interpretaría el resultado en un contexto real?**
    En un contexto real, los resultados (caudal total, consumo diario y mensual, y clasificación del consumo) proporcionan una visión clara del uso del agua de un hogar. Por ejemplo:
    *   Un `consumo_diario` y `consumo_mensual` elevados, clasificados como `Alto`, indicarían una alta demanda de agua, lo que podría llevar a facturas más altas o a la necesidad de considerar medidas de ahorro o eficiencia en el uso del agua. También podría ser un indicador para entidades de servicio público sobre patrones de consumo en ciertas áreas.
    *   La clasificación ayuda a contextualizar rápidamente el impacto del consumo, permitiendo comparaciones o la identificación de hogares con usos excepcionalmente bajos o altos.

## 8. Extensión opcional

Si desea profundizar, puede ampliar el programa para que también permita:

- calcular el consumo semanal;
- comparar el consumo de varios hogares;
- estimar el costo del agua si se conoce una tarifa por litro o por metro cúbico;
- convertir litros a metros cúbicos;
- presentar los resultados en forma tabular.

> Estas extensiones no reemplazan la solución base; son una ampliación.

## Implementación de Extensiones Opcionales

In [7]:
# Nuevas constantes para las extensiones
DIAS_SEMANA = 7
TARIFA_POR_LITRO = 0.005 # Ejemplo: 0.005 unidades monetarias por litro
LITROS_POR_METRO_CUBICO = 1000 # 1 metro cúbico = 1000 litros

In [8]:
def calcular_consumo_hogar(num_plumas, caudal_pluma=0.025, segundos_dia=86400, dias_mes=30, dias_semana=7, tarifa_por_litro=0.005, litros_por_metro_cubico=1000):
    """
    Calcula el consumo de agua de un hogar y lo clasifica.

    Args:
        num_plumas (float): Número de plumas de agua del hogar.
        caudal_pluma (float): Caudal de una pluma en litros por segundo.
        segundos_dia (int): Segundos en un día.
        dias_mes (int): Días en un mes.
        dias_semana (int): Días en una semana.
        tarifa_por_litro (float): Costo por litro de agua.
        litros_por_metro_cubico (int): Litros en un metro cúbico.

    Returns:
        dict: Un diccionario con los resultados del cálculo y la clasificación.
    """
    caudal_total = num_plumas * caudal_pluma
    consumo_diario = caudal_total * segundos_dia
    consumo_semanal = consumo_diario * dias_semana
    consumo_mensual = consumo_diario * dias_mes

    consumo_diario_m3 = consumo_diario / litros_por_metro_cubico
    consumo_semanal_m3 = consumo_semanal / litros_por_metro_cubico
    consumo_mensual_m3 = consumo_mensual / litros_por_metro_cubico

    costo_mensual = consumo_mensual * tarifa_por_litro

    nivel_consumo = ""
    if consumo_diario < 1000:
        nivel_consumo = "Bajo"
    elif 1000 <= consumo_diario <= 3000:
        nivel_consumo = "Medio"
    else:
        nivel_consumo = "Alto"

    return {
        'Número de Plumas': num_plumas,
        'Caudal Total (L/s)': caudal_total,
        'Consumo Diario (L)': consumo_diario,
        'Consumo Diario (m³)': consumo_diario_m3,
        'Consumo Semanal (L)': consumo_semanal,
        'Consumo Semanal (m³)': consumo_semanal_m3,
        'Consumo Mensual (L)': consumo_mensual,
        'Consumo Mensual (m³)': consumo_mensual_m3,
        'Costo Mensual': costo_mensual,
        'Clasificación': nivel_consumo }

### Comparación del consumo de varios hogares

In [9]:
import pandas as pd

# Definir una lista de hogares con diferentes números de plumas
hogares_plumas = [
    {'Hogar': 'Hogar A', 'Plumas': 1},
    {'Hogar': 'Hogar B', 'Plumas': 5},
    {'Hogar': 'Hogar C', 'Plumas': 10},
    {'Hogar': 'Hogar D', 'Plumas': 2},
    {'Hogar': 'Hogar E', 'Plumas': 7}]

# Calcular el consumo para cada hogar
resultados_hogares = []
for hogar in hogares_plumas:
    num_plumas = hogar['Plumas']
    resultados = calcular_consumo_hogar(num_plumas, CAUDAL_PLUMA, SEGUNDOS_DIA, DIAS_MES, DIAS_SEMANA, TARIFA_POR_LITRO, LITROS_POR_METRO_CUBICO)
    resultados['Hogar'] = hogar['Hogar']
    resultados_hogares.append(resultados)

# Convertir los resultados a un DataFrame de pandas para presentación tabular
df_comparacion = pd.DataFrame(resultados_hogares)

# Reordenar las columnas para mejor legibilidad
df_comparacion = df_comparacion[['Hogar', 'Número de Plumas', 'Caudal Total (L/s)',
                                   'Consumo Diario (L)', 'Consumo Diario (m³)',
                                   'Consumo Semanal (L)', 'Consumo Semanal (m³)',
                                   'Consumo Mensual (L)', 'Consumo Mensual (m³)',
                                   'Costo Mensual', 'Clasificación']]

# Mostrar los resultados
display(df_comparacion)

,Hogar,Número de Plumas,Caudal Total (L/s),Consumo Diario (L),Consumo Diario (m³),Consumo Semanal (L),Consumo Semanal (m³),Consumo Mensual (L),Consumo Mensual (m³),Costo Mensual,Clasificación
0,Hogar A,1,0.025,2160.0,2.16,15120.0,15.12,64800.0,64.8,324.0,Medio
1,Hogar B,5,0.125,10800.0,10.80,75600.0,75.60,324000.0,324.0,1620.0,Alto
2,Hogar C,10,0.250,21600.0,21.60,151200.0,151.20,648000.0,648.0,3240.0,Alto
3,Hogar D,2,0.050,4320.0,4.32,30240.0,30.24,129600.0,129.6,648.0,Alto
4,Hogar E,7,0.175,15120.0,15.12,105840.0,105.84,453600.0,453.6,2268.0,Alto

## 9. Documentación del código con apoyo de IA

Después de construir y probar su programa:

1. Copie su código en ChatGPT.
2. Solicite una **explicación técnica en Markdown** del código.
3. Pida además:
   - descripción de la función del programa;
   - explicación de cada sección;
   - explicación de variables, entradas, procesos y salidas;
   - observaciones sobre claridad y buenas prácticas.
4. Mejore su código con base en esa retroalimentación.
5. Actualice su repositorio en GitHub con la versión mejorada y documentada.

### Prompt sugerido para documentar el código

```text
Actúa como docente universitario experto en programación con Python.

Te voy a compartir un código en Python.
Necesito que expliques el código en formato Markdown de manera clara, técnica y ordenada.

Incluye:
1. propósito general del programa;
2. explicación de entradas, procesos y salidas;
3. descripción de cada variable importante;
4. explicación de las estructuras usadas;
5. observaciones sobre claridad, estilo y posibles mejoras;
6. una versión comentada del código, sin cambiar su lógica.

Aquí está mi código:
[PEGAR AQUÍ EL CÓDIGO]
```

In [10]:
# Nuevas constantes para las extensiones
DIAS_SEMANA = 7
TARIFA_POR_LITRO = 0.005 # Ejemplo: 0.005 unidades monetarias por litro
LITROS_POR_METRO_CUBICO = 1000 # 1 metro cúbico = 1000 litros

def calcular_consumo_hogar(num_plumas, caudal_pluma=0.025, segundos_dia=86400, dias_mes=30, dias_semana=7, tarifa_por_litro=0.005, litros_por_metro_cubico=1000):
    """
    Calcula el consumo de agua de un hogar y lo clasifica.

    Args:
        num_plumas (float): Número de plumas de agua del hogar.
        caudal_pluma (float): Caudal de una pluma en litros por segundo.
        segundos_dia (int): Segundos en un día.
        dias_mes (int): Días en un mes.
        dias_semana (int): Días en una semana.
        tarifa_por_litro (float): Costo por litro de agua.
        litros_por_metro_cubico (int): Litros en un metro cúbico.

    Returns:
        dict: Un diccionario con los resultados del cálculo y la clasificación.
    """
    # 3. Calcular el caudal total (litros por segundo)
    caudal_total = num_plumas * caudal_pluma

    # 4. Calcular el consumo diario (litros)
    consumo_diario = caudal_total * segundos_dia

    # Calcular consumo semanal (Litros y Metros Cúbicos)
    consumo_semanal = consumo_diario * dias_semana

    # 5. Calcular el consumo mensual (litros)
    consumo_mensual = consumo_diario * dias_mes

    # Convertir a metros cúbicos
    consumo_diario_m3 = consumo_diario / litros_por_metro_cubico
    consumo_semanal_m3 = consumo_semanal / litros_por_metro_cubico
    consumo_mensual_m3 = consumo_mensual / litros_por_metro_cubico

    # Estimar el costo del agua
    costo_mensual = consumo_mensual * tarifa_por_litro

    # 6. Clasificar el consumo
    nivel_consumo = ""
    if consumo_diario < 1000:
        nivel_consumo = "Bajo"
    elif 1000 <= consumo_diario <= 3000:
        nivel_consumo = "Medio"
    else:
        nivel_consumo = "Alto"

    return {
        'Número de Plumas': num_plumas,
        'Caudal Total (L/s)': caudal_total,
        'Consumo Diario (L)': consumo_diario,
        'Consumo Diario (m³)': consumo_diario_m3,
        'Consumo Semanal (L)': consumo_semanal,
        'Consumo Semanal (m³)': consumo_semanal_m3,
        'Consumo Mensual (L)': consumo_mensual,
        'Consumo Mensual (m³)': consumo_mensual_m3,
        'Costo Mensual': costo_mensual,
        'Clasificación': nivel_consumo
    }

import pandas as pd

# Definir una lista de hogares con diferentes números de plumas
hogares_plumas = [
    {'Hogar': 'Hogar A', 'Plumas': 1},
    {'Hogar': 'Hogar B', 'Plumas': 5},
    {'Hogar': 'Hogar C', 'Plumas': 10},
    {'Hogar': 'Hogar D', 'Plumas': 2},
    {'Hogar': 'Hogar E', 'Plumas': 7}
]

# Calcular el consumo para cada hogar
resultados_hogares = []
for hogar in hogares_plumas:
    num_plumas = hogar['Plumas']
    resultados = calcular_consumo_hogar(num_plumas, CAUDAL_PLUMA, SEGUNDOS_DIA, DIAS_MES, DIAS_SEMANA, TARIFA_POR_LITRO, LITROS_POR_METRO_CUBICO)
    resultados['Hogar'] = hogar['Hogar']
    resultados_hogares.append(resultados)

# Convertir los resultados a un DataFrame de pandas para presentación tabular
df_comparacion = pd.DataFrame(resultados_hogares)

# Reordenar las columnas para mejor legibilidad
df_comparacion = df_comparacion[['Hogar', 'Número de Plumas', 'Caudal Total (L/s)',
                                   'Consumo Diario (L)', 'Consumo Diario (m³)',
                                   'Consumo Semanal (L)', 'Consumo Semanal (m³)',
                                   'Consumo Mensual (L)', 'Consumo Mensual (m³)',
                                   'Costo Mensual', 'Clasificación']]

# Mostrar los resultados
display(df_comparacion)

,Hogar,Número de Plumas,Caudal Total (L/s),Consumo Diario (L),Consumo Diario (m³),Consumo Semanal (L),Consumo Semanal (m³),Consumo Mensual (L),Consumo Mensual (m³),Costo Mensual,Clasificación
0,Hogar A,1,0.025,2160.0,2.16,15120.0,15.12,64800.0,64.8,324.0,Medio
1,Hogar B,5,0.125,10800.0,10.80,75600.0,75.60,324000.0,324.0,1620.0,Alto
2,Hogar C,10,0.250,21600.0,21.60,151200.0,151.20,648000.0,648.0,3240.0,Alto
3,Hogar D,2,0.050,4320.0,4.32,30240.0,30.24,129600.0,129.6,648.0,Alto
4,Hogar E,7,0.175,15120.0,15.12,105840.0,105.84,453600.0,453.6,2268.0,Alto

## 10. Trabajo con GitHub

Una vez terminado el programa:

1. Cree un repositorio en GitHub.
2. Suba el notebook o el archivo `.py`.
3. Haga un primer commit.
4. Después de ampliar la documentación del código, haga un segundo commit.
5. Copie la URL del repositorio y consérvela para la entrega.

### Ejemplo de estructura del repositorio

```text
actividad-pluma-agua/
│
├── README.md
├── pluma_agua.py
└── Actividad_Pluma_de_Agua_Algoritmo_GitHub.ipynb
```

## 11. Comandos Git sugeridos

> **Nota:** estos comandos deben ejecutarse en la terminal, Git Bash o PowerShell.

### 11.1 Inicializar el repositorio local

```bash
git init
git add .
git commit -m "Versión inicial de la actividad pluma de agua"
```

### 11.2 Conectar con GitHub

```bash
git branch -M main
git remote add origin URL_DEL_REPOSITORIO
git push -u origin main
```

### 11.3 Subir una segunda versión con mejor documentación

```bash
git add .
git commit -m "Se mejora documentación y comentarios del código"
git push
```

## 12. Clonar el repositorio en el disco local C:

Una vez que el repositorio esté en GitHub, copie su URL y ejecute:

```bash
cd /c
git clone URL_DEL_REPOSITORIO
```

Si está usando PowerShell en Windows, también puede hacerlo así:

```powershell
cd C:\
git clone URL_DEL_REPOSITORIO
```

### Ejemplo esperado

Si su repositorio se llama:

```text
https://github.com/usuario/actividad-pluma-agua.git
```

entonces el comando sería:

```bash
git clone https://github.com/usuario/actividad-pluma-agua.git
```

Con esto se creará una carpeta del proyecto dentro de `C:\`.

## 13. Evidencia de entrega sugerida

El estudiante debe entregar:

- el enlace del repositorio en GitHub;
- el notebook o archivo `.py` funcional;
- una versión documentada del código;
- evidencia de que el repositorio fue clonado en el equipo local.

### Evidencia mínima recomendada
- captura del repositorio en GitHub;
- captura de los commits;
- captura del comando `git clone` ejecutado correctamente.

## 14. Reflexión final

Este ejercicio no trata solamente de programar.  
También muestra cómo una palabra cotidiana del Caribe colombiano puede llevarnos a:

- la historia de la hidráulica;
- la representación computacional de una magnitud física;
- el diseño de algoritmos;
- el uso responsable de herramientas como GitHub y ChatGPT en el trabajo académico.

> La programación también puede nacer de la memoria cultural y del contexto local.

## 15. Espacio para notas del estudiante

Escriba aquí una breve reflexión personal:

- ¿Qué aprendió?
- ¿Qué parte le resultó más difícil?
- ¿Qué mejoró cuando documentó el código?
- ¿Qué importancia tiene publicar y versionar su trabajo?